###
GET http://localhost:8081/persons

###
GET http://localhost:8081/persons/1

###
POST http://localhost:8081/persons
Content-Type: application/json

{
  "name": "",
  "country": "Australia",
  "salary": "10.00"
}

###
POST http://localhost:8081/persons
Content-Type: application/json

{
  "name": "Alice Wells",
  "salary": "4000.00"
}


###
POST http://localhost:8081/persons
Content-Type: application/json

{
  "name": "Alice Wells",
  "country": "Australia"
}